var quotes = [
{ character: "Darth Maul", quote: "At last we will reveal ourselves to the Jedi. At last we will have revenge." },
{ character: "Obi-Wan Kenobi", quote: "Do not defy the council, Master, not again." },
{ character: "Anakin Skywalker", quote: "Compassion, which I would define as unconditional love, is essential to a Jedi's life." },
{ character: "Princess Leia Organa", quote: "Governor Tarkin. I should have expected to find you holding Vader's leash. I recognized your foul stench when I was brought onboard." },
{ character: "Obi-Wan Kenobi", quote: "These aren't the droids you're looking for." },
{ character: "Obi-Wan Kenobi", quote: "Remember... the Force will be with you, always." },
{ character: "Obi-Wan Kenobi", quote: "Be mindful of your thoughts Anakin. They'll betray you." },
{ character: "Lando Calrissian", quote: "Princess, we'll find Han. I promise." },
{ character: "Qui-Gon Jinn", quote: "There's always a bigger fish." },
{ character: "Jango Fett", quote: "I'm just a simple man trying to make my way in the universe." },
{ character: "Darth Vader", quote: "I've been waiting for you, Obi-Wan. We meet again, at last. The circle is now complete." },
{ character: "C-3PO", quote: "Sir, the possibility of successfully navigating an asteroid field is approximately 3,720 to 1." },
{ character: "Obi-Wan Kenobi", quote: "Obi-Wan Kenobi. Obi-Wan. Now that's a name I have not heard in a long time. A long time." },
{ character: "Darth Vader", quote: "Search your feelings, you know it to be true." },
{ character: "Han Solo", quote: "Wait. I know that laugh..." },
{ character: "Emperor Palpatine", quote: "The force is with you, young Skywalker, but you are not a Jedi yet." },
{ character: "Obi-Wan Kenobi", quote: "Luke, we're gonna have company!" },
{ character: "Yoda", quote: "Told you I did. Reckless is he. ...Now, matters are worse." },
{ character: "Padme", quote: "Sometimes there are things no one can fix." },
{ character: "Obi-Wan Kenobi", quote: "A young Jedi named Darth Vader, who was a pupil of mine until he turned to evil, helped the Empire hunt down and destroy the Jedi knights." },
{ character: "Han Solo", quote: "I thought they smelled bad on the outside!" },
{ character: "Darth Vader", quote: "Obi-Wan has taught you well." },
{ character: "Emperor Palpatine", quote: "Now, young Skywalker... you will die." },
{ character: "", quote: "Do what must be done." },
{ character: "", quote: "You cannot hide forever." },
{ character: "", quote: "You are a part of the Rebel Alliance and a traitor! Take her away!" },
{ character: "", quote: "A Jedi's strength flows from the force." },
{ character: "", quote: "R2-D2, it is you, It is you!" },
{ character: "", quote: "I sense great fear in you, Skywalker. You have hate... you have anger... but you don't use them." },
{ character: "", quote: "I can save him. I can turn him back to the good side. I have to try." },
{ character: "", quote: "Attacking that battle station is not my idea of courage. It's more like, suicide." },
{ character: "", quote: "Oh no, young Jedi. You will find that it is you who are mistaken - about a great many things." },
{ character: "", quote: "Did you hear that? They shut down the main reactor. We'll be destroyed for sure. This is madness." },
{ character: "", quote: "I do believe they think I am some kind of god." },
{ character: "", quote: "Luke, when gone am I... the last of the Jedi will you be." },
{ character: "", quote: "Twice the pride, double the fall." },
{ character: "Anakin Skywalker", quote: "I will come back and free you, Mom. I promise." },
{ character: "", quote: "Down here, I am. Find a ladder, I must!" },
{ character: "", quote: "Don't call me a mindless philosopher, you overweight glob of grease." },
{ character: "", quote: "You were the chosen one! It was said that you would destroy the Sith, not join them." },
{ character: "", quote: "Just being around her again is... intoxicating." },
{ character: "", quote: "All mentors have a way of seeing more of our faults than we would like. It's the only way we grow." },
{ character: "", quote: "Into the garbage chute, flyboy!" },
{ character: "", quote: "Our fate is in your hands." },
{ character: "", quote: "Midi-chlorians are a microscopic life form that resides within all living cells." },
{ character: "", quote: "Would it help if I got out and pushed?" },
{ character: "", quote: "I'm a member of the Imperial Senate on a diplomatic mission to Alderaan." },
{ character: "", quote: "I'm terribly sorry about all this. After all, he's only a Wookiee." },
{ character: "", quote: "You may have been a good smuggler, but now you're Bantha fodder." },
{ character: "", quote: "You were right about me. Tell your sister... you were right." },
{ character: "", quote: "Commander, tear this ship apart until you've found those plans. And bring me the passengers, I want them alive!" },
{ character: "", quote: "I have failed you Anakin. I have failed you." },
{ character: "", quote: "The Jedi are selfless, they only care about others." },
{ character: "", quote: "How wude." },
{ character: "", quote: "That is the sound of a thousand terrible things headed this way." },
{ character: "", quote: "Don't be too proud of this technological terror you've constructed." },
{ character: "", quote: "You were right about one thing, Master. The negotiations were short." },
{ character: "", quote: "I know." },
{ character: "", quote: "It's against my programming to impersonate a deity." },
{ character: "", quote: "You still have much to learn, my young padawan." },
{ character: "", quote: "The force surrounds us and penetrates us. It binds the galaxy together." },
{ character: "", quote: "Train yourself to let go of everything you fear to lose." },
{ character: "", quote: "That's a good story. I think you just can't bear to let a gorgeous guy like me out of your sight." },
{ character: "", quote: "This bounty hunter is my kind of scum. Fearless and inventive." },
{ character: "", quote: "Use the Force, Luke." },
{ character: "", quote: "There is good in him. I've felt it." },
{ character: "", quote: "Jedi Masters don't go crazy, they just get eccentric." },
{ character: "", quote: "Right now I feel like I could take on the whole Empire myself." },
{ character: "", quote: "The Sith rely on their passion for their strength. They think inward, only about themselves." },
{ character: "", quote: "Boring conversation anyway." },
{ character: "", quote: "No one can kill a Jedi." },
{ character: "Yoda", quote: "No more training do you require. Already know you that which you need." },
{ character: "", quote: "Well, short help is better than no help at all." },
{ character: "", quote: "I truly... deeply... love you and before we die I want you to know." },
{ character: "", quote: "Soon will I rest, yes, forever sleep. Earned it I have. Twilight is upon me, soon night must fall." },
{ character: "", quote: "You fool! I have been trained in your Jedi arts by Count Dooku." },
{ character: "", quote: "Oh, Han, it's not like that at all. He's my brother." },
{ character: "", quote: "Love won't save you, Padme. Only my new powers can do that." },
{ character: "", quote: "He will not let me down. He never has." },
{ character: "", quote: "This is some rescue. You came in here and you didn't have a plan for getting out?" },
{ character: "Opening title", quote: "A Long Time Ago In A Galaxy Far Far Away..." },
{ character: "", quote: "Droids don't pull people's arms outta their sockets when they lose... Wookies are known to do that..." },
{ character: "", quote: "Why you stuck-up, half-witted, scruffy-looking nerf-herder!" },
{ character: "", quote: "I suggest a new strategy, R2. Let the wookiee win." },
{ character: "", quote: "Don't make me destroy you." },
{ character: "", quote: "One thing's for sure, we're all going to be a lot thinner." },
{ character: "", quote: "I've got a very bad feeling about this." },
{ character: "C-3PO", quote: "R2-D2, you know better than to trust a strange computer!" },
{ character: "", quote: "General Grievous, you're shorter than I expected." },
{ character: "", quote: "There's nothing for me here now. I want to learn the ways of the Force and be a Jedi, like my father before me." },
{ character: "", quote: "It's a trap!" },
{ character: "", quote: "If there's a bright centre to the universe, you're on the planet that it's farthest from." },
{ character: "", quote: "Greed can be a very powerful ally." },
{ character: "", quote: "We seem to be made to suffer. It's our lot in life." },
{ character: "", quote: "Your thoughts betray you father. I feel the good in you. The conflict." },
{ character: "", quote: "Anakin, you're breaking my heart! And you're going down a path I cannot follow!" },
{ character: "", quote: "Just for once, let me look on you with my own eyes." },
{ character: "", quote: "Clear your mind must be, if you are to discover the real villains behind this plot." },
{ character: "", quote: "Listen to them, they're dying, R2. Curse my metal body. I wasn't fast enough. It's all my fault. My poor master." },
{ character: "", quote: "Look, Your Worshipfulness, let's get one thing straight... I take orders from one person! Me!" },
{ character: "", quote: "I can't do it, R2. I can't go on alone." },
{ character: "", quote: "Sometimes we must do what is requested of us." },
{ character: "", quote: "So this is how liberty dies, with thunderous applause." },
{ character: "", quote: "Look, good against remotes is one thing, good against the living, that's something else." },
{ character: "Obi-Wan Kenobi", quote: "Luke, I don't want to lose you to the Emperor the way I lost Vader." },
{ character: "", quote: "The Force runs strong in my family. My father has it. I have it. And... my sister has it. Yes. It's you, Leia." },
{ character: "", quote: "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering." },
{ character: "", quote: "You are unwise to lower your defenses..." },
{ character: "", quote: "I sense something; a presence I've not felt since..." },
{ character: "", quote: "Beware of the dark side." },
{ character: "", quote: "Ready are you? What know you of ready? For eight hundred years have I trained Jedi. My own counsel will I keep on who is to be trained." },
{ character: "", quote: "Don't center on your anxieties, Obi-Wan." },
{ character: "", quote: "Pain, suffering, death I feel. Something terrible has happened. Young Skywalker is in pain. Terrible pain." },
{ character: "", quote: "Only a master of evil, Darth." },
{ character: "Emperor Palpatine", quote: "Everything is proceeding as I have foreseen." },
{ character: "", quote: "You don't know how hard I found it, signing the order to terminate your life." },
{ character: "", quote: "Dreams pass in time." },
{ character: "", quote: "This party's over." },
{ character: "C-3PO", quote: "He's holding a thermal detonator!" },
{ character: "", quote: "Are you an angel? I've heard the deep space pilots talk about them. They're the most beautiful creatures in the universe." },
{ character: "", quote: "You refer to the prophecy of The One, who will bring balance to the Force. You believe it's this boy?" },
{ character: "", quote: "Scoundrel? Scoundrel? I like the sound of that." },
{ character: "", quote: "In time, you will learn to trust your feelings. Then, you will be invincible." },
{ character: "", quote: "Without the midi-chlorians, life could not exist, and we would have no knowledge of the Force." },
{ character: "", quote: "There's no mystical energy field that controls my destiny." },
{ character: "", quote: "You must repair him! Sir, if any of my circuits or gears will help, I'll gladly donate them." },
{ character: "", quote: "Size matters not. Look at me. Judge me by my size, do you? Hmm? Hmm." },
{ character: "", quote: "All who gain power are afraid to lose it." },
{ character: "", quote: "Patience, my blue friend." },
{ character: "", quote: "I can only protect you, I cannot fight a war for you." },
{ character: "Han Solo", quote: "Lando's not a system he's a man!" },
{ character: "", quote: "I don't want to hear anymore about Obi-Wan. The Jedi turned against me! Don't you turn against me!" },
{ character: "", quote: "You must feel the force around you. Here, between you, me, the tree, the rock... everywhere! Yes, even between this land and that ship!" },
{ character: "", quote: "If so powerful you are, why leave?" },
{ character: "", quote: "It is possible that the war itself has been only one further move in some greater game." },
{ character: "", quote: "Do not assume anything. Clear, your mind must be." },
{ character: "Han Solo", quote: "Great, kid! Don't get cocky." },
{ character: "", quote: "You can't win. But there are alternatives to fighting." },
{ character: "", quote: "Difficult to see. Always in motion is the future." },
{ character: "", quote: "Good Anakin. Good. Kill him. Kill him now." },
{ character: "", quote: "Anger, fear, aggression; the dark side of the Force are they. Easily they flow, quick to join you in a fight." },
{ character: "", quote: "Luke, you can destroy the Emperor. He has foreseen this. It is your destiny. Join me, and together we can rule the galaxy as father and son." },
{ character: "", quote: "I'm not afraid to die." },
{ character: "", quote: "Mudhole? Slimy? My home this is!" },
{ character: "Lando Calrissian", quote: "You look absolutely beautiful. You truly belong here with us among the clouds." },
{ character: "", quote: "Either shut him up or shut him down!" },
{ character: "", quote: "Oh my. Space travel sound rather perilous. I can assure you they will never get me on one of those dreadful Star Ships." },
{ character: "Luke Skywalker", quote: "I'm Luke Skywalker, I'm here to rescue you." },
{ character: "", quote: "Your overconfidence is your weakness." },
{ character: "Yoda", quote: "Anger, fear, aggression... the dark side are they. Once you start down the dark path, forever will it dominate your destiny." },
{ character: "", quote: "Every generation has a legend. Every journey has a first step. Every saga has a beginning." },
{ character: "", quote: "Always two there are, no more, no less: a master and an apprentice." },
{ character: "", quote: "Victory? Victory, you say? Master Obi-Wan, not victory. The shroud of the Dark Side has fallen. Begun, the Clone War has!" },
{ character: "", quote: "Uh, we had a slight weapons malfunction, but uh, everything's perfectly all right now." },
{ character: "Obi-Wan Kenobi", quote: "That boy is our last hope." },
{ character: "Yoda", quote: "Luminous beings are we. Not this crude matter." },
{ character: "", quote: "Oh, my! What have you done? I'm BACKWARDS. You flea-bitten furball! Only an overgrown mop-head like you would be stupid enough to..." },
{ character: "", quote: "Luke... Luke... do not... do not underestimate the powers of the Emperor or suffer your father's fate you will." },
{ character: "", quote: "The ability to speak does not make you intelligent." },
{ character: "", quote: "He was meant to root out the Rebels, not give them hope. His sacrifice will only inspire them..." },
{ character: "Princess Leia Organa", quote: "You have your moments. Not many of them, but you do have them." },
{ character: "", quote: "The council has granted me permission to train you. You will be a Jedi, I promise." },
{ character: "", quote: "For over a thousand generations, the Jedi Knights were the guardians of peace and justice in the Old Republic." },
{ character: "", quote: "Ex-squeeze me, but the mostest safest place would be Gunga City." },
{ character: "", quote: "Boy, it's lucky you have these compartments!" },
{ character: "", quote: "The drums of conflict are my beating heart." },
{ character: "", quote: "I find your lack of faith disturbing." },
{ character: "", quote: "That's your uncle talking." },
{ character: "", quote: "The Force is strong with him. The son of Skywalker must not become a Jedi." },
{ character: "", quote: "I can hold it... I can hold it... I CAN'T HOLD IT!" },
{ character: "", quote: "In his belly you will find a new definition of pain and suffering as you are slowly digested over a thousand years." },
{ character: "", quote: "Then I'll see you in hell!" },
{ character: "", quote: "He is as clumsy as he is stupid. General, prepare your troops for a surface attack." },
{ character: "", quote: "Pass on what you have learned." },
{ character: "", quote: "From the moment I met you, all those years ago, not a day has gone by when I haven't thought of you." },
{ character: "", quote: "Look, I ain't in this for your revolution, and I'm not in it for you, Princess. I expect to be well paid. I'm in it for the money." },
{ character: "", quote: "Luke, you switched off your targeting computer - what's wrong?" },
{ character: "", quote: "Will someone get this big walking carpet out of my way?" },
{ character: "", quote: "Mom, you said that the biggest problem in the universe is no one helps each other." },
{ character: "", quote: "Your eyes can deceive you; don't trust them." },
{ character: "Han Solo", quote: "Uh, uh... negative, negative. We had a reactor leak here now. Give us a few minutes to lock it down. Large leak, very dangerous." },
{ character: "", quote: "Hmph. Adventure. Heh. Excitement. Heh. A Jedi craves not these things. You are reckless." },
{ character: "", quote: "You may dispense with the pleasantries, Commander. I am here to put you back on schedule." },
{ character: "", quote: "Master Kenobi, you disappoint me. Yoda holds you in such high esteem. Surely you can do better!" },
{ character: "", quote: "He's quite clever, you know... for a human being." },
{ character: "Luke Skywalker", quote: "This is Red 5, I'm going in." },
{ character: "", quote: "Because you are my Son!" },
{ character: "", quote: "I haven't gone by the name of Obi-Wan since... oh, before you were born." },
{ character: "", quote: "He will join us or die, my master." },
{ character: "", quote: "I think I'm finally getting the hang of this flying business." },
{ character: "", quote: "Never tell me the odds." },
{ character: "C-3PO", quote: "And I am C-3PO, human-cyborg relations. And this is my counterpart R2D2." },
{ character: "", quote: "She may not look like much, but she's got it where it counts, kid." },
{ character: "", quote: "Jedi business. Go back to your drinks." },
{ character: "", quote: "It's not wise to upset a Wookiee." },
{ character: "", quote: "I don't know who you are or where you've come from, but from now on you'll do as I say, okay?" },
{ character: "", quote: "How you doin\" Chewbacca? Still hanging around with this loser?" },
{ character: "", quote: "Some day you're gonna be wrong, I just hope I'm there to see it." },
{ character: "", quote: "The ability to destroy a planet is insignificant next to the power of the Force." },
{ character: "", quote: "Crush them! Make them suffer!" },
{ character: "", quote: "Use my knowledge, I beg you." },
{ character: "", quote: "I felt a great disturbance in the force, as if millions of voices suddenly cried out in terror and were suddenly silenced." },
{ character: "", quote: "Anakin, please tell me this isn't another of your patented rescues where we'll require the whole Republic army to get safely away." },
{ character: "", quote: "I have you now!" },
{ character: "", quote: "But which one was destroyed? The master or the apprentice?" },
{ character: "", quote: "I don't believe what I'm hearing... Obi-Wan was right. You've changed." },
{ character: "", quote: "Always on the move." },
{ character: "", quote: "The Dark Side of the Force is the pathway to many abilities some consider to be... Unnatural." },
{ character: "Yoda", quote: "When 900 years old, you reach... Look as good, you will not." },
{ character: "", quote: "You were my brother, Anakin. I loved you." },
{ character: "", quote: "Army or not. You must realize, you are doomed." },
{ character: "", quote: "Hold your fire. There's no life forms. It must have short-circuited." },
{ character: "", quote: "Captain, being held by you isn't quite enough to get me excited." },
{ character: "", quote: "You can forget your troubles with those Imperial slugs. I told you I'd outrun 'em. Don't everyone thank me at once." },
{ character: "", quote: "You can't win, Darth. Strike me down, and I will become more powerful than you could possibly imagine." },
{ character: "", quote: "You'll be dead!" },
{ character: "Luke Skywalker", quote: "Nooooooooooooooooooo!" },
{ character: "", quote: "Attachment is forbidden. Possession is forbidden. Compassion, which I would define as unconditional love, is essential to a Jedi's life." },
{ character: "", quote: "I sense a great deal of confusion in you, young Skywalker. There's much fear that clouds your judgement." },
{ character: "", quote: "Keep your concentration here and now, where it belongs." },
{ character: "", quote: "Into exile I must go, failed I have." },
{ character: "", quote: "Watch your mouth kid, or you'll find yourself floating home." },
{ character: "", quote: "Aren't you a little short for a stormtrooper?" },
{ character: "", quote: "Truly wonderful, the mind of a child is." },
{ character: "", quote: "Laugh it up, Fuzz ball." },
{ character: "", quote: "Promise. Promise me you will train the boy. He... is the chosen one... he will bring balance. Train him." },
{ character: "Darth Vader", quote: "Impressive, most impressive." },
{ character: "", quote: "Oh my goodness, shut me down! Machines making machines. How perverse." },
{ character: "", quote: "I'm Luke Skywalker. I'm here to rescue you." },
{ character: "", quote: "Keep your distance, Chewie, but don't, y'know, look like you're keeping your distance." },
{ character: "", quote: "Don't get technical with me. What mission? What are you talking about? I've just about had enough of you. Go that way, you'll be malfunctioning in a day you near-sighted scrap pile." },
{ character: "", quote: "I have waited a long time for this moment, my little green friend. At last, the Jedi are no more." },
{ character: "", quote: "Blind we are, if creation of this clone army we could not see." },
{ character: "Darth Vader", quote: "Asteroids do not concern me, Admiral. I want that ship, not excuses." },
{ character: "", quote: "A tremor in the Force. The last time I felt it was in the presence of my old master." },
{ character: "", quote: "Bargain rather than fight? He's no Jedi." },
{ character: "", quote: "The Force can have a strong influence on the weak-minded." },
{ character: "", quote: "Aaaaaaargh!" },
{ character: "", quote: "Now, be brave and don't look back. Don't look back." },
{ character: "", quote: "Patience, use the Force, think!" },
{ character: "", quote: "I don't like you either. You just watch yourself. We're wanted men. I have the death sentence on twelve systems." },
{ character: "", quote: "The Jedi are extinct, their fire has gone out of the universe. You, my friend, are all that's left of their religion." },
{ character: "", quote: "I hope so Commander, for your sake. The Emperor is not as forgiving as I am." },
{ character: "", quote: "What a piece of junk!" },
{ character: "", quote: "I'm getting too old for this sort of thing." },
{ character: "", quote: "You fool! I've been trained in your Jedi arts by Count Dooku." },
{ character: "", quote: "Make, at least, 20 people smile in a day." },
{ character: "", quote: "Mmm. Lost a planet, Master Obi-Wan has. How embarrassing." },
{ character: "", quote: "Bring 'em on, I'd prefer a straight fight to all this sneaking around." },
{ character: "Obi-Wan Kenobi", quote: "In my experience, there's no such thing as luck." },
{ character: "", quote: "I guess you don't know everything about women yet." },
{ character: "", quote: "Evacuate in our moment of triumph? I think you overestimate their chances." },
{ character: "", quote: "To a dark place this line of thought will carry us. Great care we must take." },
{ character: "", quote: "All his life has he looked away... to the future, to the horizon. Never his mind on where he was. Hmm? What he was doing." },
{ character: "", quote: "I was not elected to watch my people suffer and die while you discuss this invasion in a committee!" },
{ character: "", quote: "Wonderful girl. Either I'm going to kill her or I'm beginning to like her." },
{ character: "", quote: "Why do I sense we've picked up another pathetic life-form?" },
{ character: "", quote: "These blast points - too accurate for sandpeople. Only imperial stormtroopers are so precise." },
{ character: "", quote: "How ya feeling kid? You don't look so bad to me. You look strong enough to pull the ears off a gundark." },
{ character: "", quote: "No, my father didn't fight in the Clone Wars. He was a navigator on a spice freighter." },
{ character: "", quote: "You were to bring balance to the force, not leave it in darkness." },
{ character: "", quote: "Mesa called JaJa Binks, mesa youse humble servant!" },
{ character: "", quote: "A Jedi uses the force for knowledge and defense, never for attack." },
{ character: "", quote: "I don't like sand. It's coarse and rough and irritating and it gets everywhere. Not like here. Here everything is soft and smooth." },
{ character: "", quote: "Me? A Master? I'm overwhelmed, sir. But the Council elects its own members. They will never accept this." },
{ character: "", quote: "One truth, one hate." },
{ character: "", quote: "Thank the maker!" },
{ character: "Mon Mothma", quote: "Many Bothans died to bring us this information." },
{ character: "", quote: "Help me Obi-Wan Kenobi, you're my only hope." },
{ character: "", quote: "The Force is what gives a Jedi his power. It's an energy field created by all living things. It surrounds us and penetrates us. It binds the galaxy together." },
{ character: "", quote: "If you have warriors, now is the time." },
{ character: "", quote: "This will be a day long remembered. It has seen the end of Kenobi, and will soon see the end of the rebellion." },
{ character: "", quote: "I recognized your foul stench when I was brought on board." },
{ character: "", quote: "You've never heard of the Millennium Falcon?... It's the ship that made the Kessel run in less than 12 parsecs." },
{ character: "", quote: "Son, my place is here, my future is here. It is time for you to let go." },
{ character: "", quote: "We are indebted to you for your bravery, Obi-Wan Kenobi. And you, young Skywalker; we will watch your career with great interest." },
{ character: "", quote: "I'm altering the deal. Pray I don't alter it any further." },
{ character: "", quote: "To be angry is to be human." },
{ character: "", quote: "You came in that thing? You're braver than I thought." },
{ character: "", quote: "Attachment leads to jealousy. The shadow of greed that is." },
{ character: "", quote: "You know better than to trust a strange computer." },
{ character: "", quote: "Someday I'll be the most powerful Jedi ever." },
{ character: "", quote: "You were the Chosen one!" },
{ character: "", quote: "Traveling through hyperspace ain't like dusting crops, farm boy." },
{ character: "", quote: "You can either profit by this or be destroyed. It's your choice, but I warn you not to underestimate my power." },
{ character: "C-3PO", quote: "R2, why did you have to be so brave?" },
{ character: "Han Solo", quote: "Jabba, you're a wonderful human being." },
{ character: "", quote: "All who gain power are afraid to lose it." },
{ character: "", quote: "Help me Obi-Wan Kenobi. You're my only hope." },
{ character: "", quote: "You're asking me to be rational. That is something I know I cannot do. Believe me, I wish I could just wish away my feelings, but I can't." },
{ character: "", quote: "What if the democracy we thought we were serving no longer exists, and the Republic has become the very evil we've been fighting to destroy?" },
{ character: "C-3PO", quote: "Hello. I don't believe we have been introduced. R2-D2? A pleasure to meet you. I am C-3PO, Human-Cyborg Relations." },
{ character: "", quote: "Faith in your new apprentice, misplaced may be. As is your faith in the dark side of the Force." },
{ character: "", quote: "Give yourself to the Dark Side. It is the only way you can save your friends. Yes your thoughts betray you." },
{ character: "", quote: "You must unlearn what you have learned." },
{ character: "", quote: "Now don't you forget this! Why I should stick my neck out for you is far beyond my capacity!" },
{ character: "", quote: "Feel the Force!" },
{ character: "", quote: "I am not training him." },
{ character: "", quote: "Something's happening. I'm not the Jedi I should be. I want more. And I know I shouldn't." },
{ character: "", quote: "Feel, don't think." },
{ character: "Darth Vader", quote: "I've been waiting for you, Obi-Wan. We meet again, at last. The circle is now complete. When I left you, I was but the learner; now I am the master." },
{ character: "", quote: "I will not condone a course of action that will lead us to war." },
{ character: "", quote: "At the thought of not being with you, I can't breathe." },
{ character: "", quote: "Don't try to frighten us with your sorcerous ways, Lord Vader." },
{ character: "", quote: "It is obvious that this contest cannot be decided by our knowledge of the Force... but by our skills with a lightsaber." },
{ character: "Emperor Palpatine", quote: "Wipe them out. All of them." },
{ character: "", quote: "Look, sir: Droids." },
{ character: "", quote: "If you're not with me, then you're my enemy." },
{ character: "", quote: "May the force be with you." },
{ character: "", quote: "A Jedi Knight? Jeez, I'm out of it for a little while, everyone gets delusions of grandeur!" },
{ character: "", quote: "These Federation types are cowards. The negotiations will be short." },
{ character: "", quote: "Your powers are weak, old man." },
{ character: "", quote: "Through the force, things you will see. Other places. The future... the past. Old friends long gone." },
{ character: "", quote: "Hokey religions and ancient weapons are no match for a good blaster at your side, kid." },
{ character: "", quote: "Clear your mind of questions." },
{ character: "Han Solo", quote: "Great shot kid, that was one in a million." },
{ character: "", quote: "Wars not make one great." },
{ character: "C-3PO", quote: "Let the Wookiee win." },
{ character: "", quote: "This is some rescue! You came in here, but didn't you have a plan for getting out?" },
{ character: "", quote: "That... is why you fail." },
{ character: "Luke Skywalker", quote: "I don't sense anything." },
{ character: "", quote: "Mos Eisley spaceport. You will never find a more wretched hive of scum and villainy." },
{ character: "", quote: "Not to worry. We're still flying half a ship." },
{ character: "", quote: "Another happy landing." },
{ character: "", quote: "Rejoice for those around you who transform into the Force." },
{ character: "", quote: "The Force is strong with this one." },
{ character: "", quote: "I see you becoming the greatest of all the Jedi, Anakin. Even more powerful than Master Yoda." },
{ character: "", quote: "No. I am your Father." },
{ character: "", quote: "It is too late for me, son. The Emperor will show you the true nature of the Force. He is your master now." },
{ character: "", quote: "The Chancellor's right, Senator. We'll be quite safe. He won several cups for airspeeder racing back on Naboo." },
{ character: "Yoda", quote: "No! Try not. Do, or do not. There is no try." },
{ character: "", quote: "Anything is possible." },
{ character: "", quote: "Your arrogance blinds you." },
{ character: "", quote: "I'm haunted by the kiss that you should never have given me. My heart is beating... hoping that kiss will not become a scar." },
{ character: "", quote: "Only a sith deals in absolutes." },
{ character: "", quote: "We live in a real world, Annie. Come back to it." },
{ character: "", quote: "So, what do you think? You think a princess and a guy like me..." },
{ character: "", quote: "Don't center on your anxieties, Obi-Wan. Keep your concentration here and now, where it belongs." },
{ character: "", quote: "I'll be careful." },
{ character: "", quote: "Who's the more foolish: the fool, or the fool who follows him?" },
{ character: "", quote: "General, prepare your men." },
{ character: "", quote: "The strong survive, the weak die. That's the way the galaxy works. The day we forgot that, we became everyone's lackey." },
{ character: "", quote: "We have powerful friends. You're going to regret this." },
{ character: "", quote: "I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything." },
{ character: "", quote: "Maybe you'd like it back in your cell, your highness." },
{ character: "", quote: "I want them alive - no disintegrations!" },
{ character: "", quote: "A Jedi must have the deepest commitment, the most serious mind." },
{ character: "Han Solo", quote: "I think my eyes are getting better. Instead of a big dark blur, I see a big light blur." },
{ character: "", quote: "We have a new enemy, the young Rebel who destroyed the Death Star. I have no doubt this boy is the offspring of Anakin Skywalker." },
{ character: "", quote: "Jabba's put a price on your head so large, every bounty hunter in the galaxy will be looking for you." },
{ character: "C-3PO", quote: "My parts are showing? Oh, my goodness, oh!" },
{ character: "Obi-Wan Kenobi", quote: "That's no moon, it's a space station." },
{ character: "Palpatine", quote: "The Force is strong with you. A powerful Sith you will become. Henceforth, you shall be known as Darth... Vader." },
{ character: "Lando Calrissian", quote: "You slimy, double-crossing, no-good swindler. You've got a lot of guts coming here, after what you pulled." },
{ character: "Obi-Wan Kenobi", quote: "Soon, I will have a new apprentice. One far younger, and more powerful." },
{ character: "Han Solo", quote: "You're all clear, kid! Now let's blow this thing and go home!" },
{ character: "Han Solo", quote: "He's the brains, sweetheart!" },
{ character: "Obi-Wan Kenobi", quote: "You will find that many of the truths we cling to depend greatly on our own point of view." },
{ character: "Anakin Skywalker", quote: "I'm a person, and my name is Anakin!" },
{ character: "Admiral Motti", quote: "This station is now the ultimate power in the universe! I suggest we use it." },
{ character: "Padme", quote: "Hold me, like you did by the lake on Naboo; so long ago when there was nothing but our love. No politics, no plotting, no war." },
{ character: "Shmi Skywalker", quote: "You can't stop the change any more than you can stop the suns from setting." },
{ character: "Yoda", quote: "Death is a natural part of life." }
];

module.exports = function() {
  return quotes[Math.floor(Math.random() * quotes.length)].quote
}

module.exports.withCharacter = function() {
  return quotes[Math.floor(Math.random() * quotes.length)]
}

module.exports.quotes = quotes