const quotes = [
  { character: "Darth Maul", quote: "At last we will reveal ourselves to the Jedi. At last we will have revenge.", movie: "The Phantom Menace" },
  { character: "Obi-Wan Kenobi", quote: "Do not defy the council, Master, not again.", movie: "The Phantom Menace" },
  { character: "Anakin Skywalker", quote: "Compassion, which I would define as unconditional love, is essential to a Jedi's life.", movie: "Attack of the Clones" },
  { character: "Princess Leia Organa", quote: "Governor Tarkin. I should have expected to find you holding Vader's leash. I recognized your foul stench when I was brought onboard.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "These aren't the droids you're looking for.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "Remember... the Force will be with you, always.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "Be mindful of your thoughts Anakin. They'll betray you.", movie: "Attack of the Clones" },
  { character: "Lando Calrissian", quote: "Princess, we'll find Han. I promise.", movie: "Return of the Jedi" },
  { character: "Qui-Gon Jinn", quote: "There's always a bigger fish.", movie: "The Phantom Menace" },
  { character: "Jango Fett", quote: "I'm just a simple man trying to make my way in the universe.", movie: "Attack of the Clones" },
  { character: "Darth Vader", quote: "I've been waiting for you, Obi-Wan. We meet again, at last. The circle is now complete.", movie: "A New Hope" },
  { character: "C-3PO", quote: "Sir, the possibility of successfully navigating an asteroid field is approximately 3,720 to 1.", movie: "The Empire Strikes Back" },
  { character: "Obi-Wan Kenobi", quote: "Obi-Wan Kenobi. Obi-Wan. Now that's a name I have not heard in a long time. A long time.", movie: "A New Hope" },
  { character: "Darth Vader", quote: "Search your feelings, you know it to be true.", movie: "The Empire Strikes Back" },
  { character: "Han Solo", quote: "Wait. I know that laugh...", movie: "Return of the Jedi" },
  { character: "Emperor Palpatine", quote: "The force is with you, young Skywalker, but you are not a Jedi yet.", movie: "Return of the Jedi" },
  { character: "Han Solo", quote: "Luke, we're gonna have company!", movie: "A New Hope" },
  { character: "Yoda", quote: "Told you I did. Reckless is he. ...Now, matters are worse.", movie: "The Empire Strikes Back" },
  { character: "Padmé Amidala", quote: "Sometimes there are things no one can fix.", movie: "Attack of the Clones" },
  { character: "Obi-Wan Kenobi", quote: "A young Jedi named Darth Vader, who was a pupil of mine until he turned to evil, helped the Empire hunt down and destroy the Jedi knights.", movie: "A New Hope" },
  { character: "Han Solo", quote: "I thought they smelled bad on the outside!", movie: "The Empire Strikes Back" },
  { character: "Darth Vader", quote: "Obi-Wan has taught you well.", movie: "Return of the Jedi" },
  { character: "Emperor Palpatine", quote: "Now, young Skywalker... you will die.", movie: "Return of the Jedi" },
  { character: "Darth Sidious", quote: "Do what must be done.", movie: "Revenge of the Sith" },
  { character: "Darth Sidious", quote: "You cannot hide forever.", movie: "Revenge of the Sith" },
  { character: "Darth Vader", quote: "You are a part of the Rebel Alliance and a traitor! Take her away!", movie: "A New Hope" },
  { character: "Yoda", quote: "A Jedi's strength flows from the force.", movie: "The Empire Strikes Back" },
  { character: "C-3PO", quote: "R2-D2, it is you, It is you!", movie: "A New Hope" },
  { character: "Emperor Palpatine", quote: "I sense great fear in you, Skywalker. You have hate... you have anger... but you don't use them.", movie: "Return of the Jedi" },
  { character: "Luke Skywalker", quote: "I can save him. I can turn him back to the good side. I have to try.", movie: "Return of the Jedi" },
  { character: "Han Solo", quote: "Attacking that battle station is not my idea of courage. It's more like, suicide.", movie: "A New Hope" },
  { character: "Emperor Palpatine", quote: "Oh no, young Jedi. You will find that it is you who are mistaken - about a great many things.", movie: "Return of the Jedi" },
  { character: "C-3PO", quote: "Did you hear that? They shut down the main reactor. We'll be destroyed for sure. This is madness.", movie: "A New Hope" },
  { character: "C-3PO", quote: "I do believe they think I am some kind of god.", movie: "Return of the Jedi" },
  { character: "Yoda", quote: "Luke, when gone am I... the last of the Jedi will you be.", movie: "Return of the Jedi" },
  { character: "Count Dooku", quote: "Twice the pride, double the fall.", movie: "Revenge of the Sith" },
  { character: "Anakin Skywalker", quote: "I will come back and free you, Mom. I promise.", movie: "The Phantom Menace" },
  { character: "Yoda", quote: "Down here, I am. Find a ladder, I must!", movie: "Attack of the Clones" },
  { character: "C-3PO", quote: "Don't call me a mindless philosopher, you overweight glob of grease.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "You were the chosen one! It was said that you would destroy the Sith, not join them.", movie: "Revenge of the Sith" },
  { character: "Anakin Skywalker", quote: "Just being around her again is... intoxicating.", movie: "Attack of the Clones" },
  { character: "Padmé Amidala", quote: "All mentors have a way of seeing more of our faults than we would like. It's the only way we grow.", movie: "Attack of the Clones" },
  { character: "Princess Leia Organa", quote: "Into the garbage chute, flyboy!", movie: "A New Hope" },
  { character: "Queen Amidala", quote: "Our fate is in your hands.", movie: "The Phantom Menace" },
  { character: "Qui-Gon Jinn", quote: "Midi-chlorians are a microscopic life form that resides within all living cells.", movie: "The Phantom Menace" },
  { character: "Leia Organa", quote: "Would it help if I got out and pushed?", movie: "The Empire Strikes Back" },
  { character: "Princess Leia Organa", quote: "I'm a member of the Imperial Senate on a diplomatic mission to Alderaan.", movie: "A New Hope" },
  { character: "C-3PO", quote: "I'm terribly sorry about all this. After all, he's only a Wookiee.", movie: "The Empire Strikes Back" },
  { character: "Jabba the Hutt", quote: "You may have been a good smuggler, but now you're Bantha fodder.", movie: "Return of the Jedi" },
  { character: "Darth Vader", quote: "You were right about me. Tell your sister... you were right.", movie: "Return of the Jedi" },
  { character: "Darth Vader", quote: "Commander, tear this ship apart until you've found those plans. And bring me the passengers, I want them alive!", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "I have failed you Anakin. I have failed you.", movie: "Revenge of the Sith" },
  { character: "Anakin Skywalker", quote: "The Jedi are selfless, they only care about others.", movie: "Attack of the Clones" },
  { character: "Jar Jar Binks", quote: "How wude.", movie: "The Phantom Menace" },
  { character: "Obi-Wan Kenobi", quote: "That is the sound of a thousand terrible things headed this way.", movie: "Attack of the Clones" },
  { character: "Darth Vader", quote: "Don't be too proud of this technological terror you've constructed.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "You were right about one thing, Master. The negotiations were short.", movie: "The Phantom Menace" },
  { character: "Han Solo", quote: "I know.", movie: "The Empire Strikes Back" },
  { character: "C-3PO", quote: "It's against my programming to impersonate a deity.", movie: "Return of the Jedi" },
  { character: "Yoda", quote: "You still have much to learn, my young padawan.", movie: "Attack of the Clones" },
  { character: "Obi-Wan Kenobi", quote: "The force surrounds us and penetrates us. It binds the galaxy together.", movie: "A New Hope" },
  { character: "Yoda", quote: "Train yourself to let go of everything you fear to lose.", movie: "Revenge of the Sith" },
  { character: "", quote: "That's a good story. I think you just can't bear to let a gorgeous guy like me out of your sight.", movie: "" },
  { character: "Jabba the Hutt", quote: "This bounty hunter is my kind of scum. Fearless and inventive.", movie: "Return of the Jedi" },
  { character: "Obi-Wan Kenobi", quote: "Use the Force, Luke.", movie: "A New Hope" },
  { character: "Luke Skywalker", quote: "There is good in him. I've felt it.", movie: "Return of the Jedi" },
  { character: "Anakin Skywalker", quote: "Jedi Masters don't go crazy, they just get eccentric.", movie: "Attack of the Clones" },
  { character: "Luke Skywalker's copilot", quote: "Right now I feel like I could take on the whole Empire myself.", movie: "The Empire Strikes Back" },
  { character: "Anakin Skywalker", quote: "The Sith rely on their passion for their strength. They think inward, only about themselves.", movie: "Revenge of the Sith" },
  { character: "Han Solo", quote: "Boring conversation anyway.", movie: "A New Hope" },
  { character: "Anakin Skywalker", quote: "No one can kill a Jedi.", movie: "Attack of the Clones" },
  { character: "Yoda", quote: "No more training do you require. Already know you that which you need.", movie: "Return of the Jedi" },
  { character: "Han Solo", quote: "Well, short help is better than no help at all.", movie: "Return of the Jedi" },
  { character: "Padmé Amidala", quote: "I truly... deeply... love you and before we die I want you to know.", movie: "Attack of the Clones" },
  { character: "Yoda", quote: "Soon will I rest, yes, forever sleep. Earned it I have. Twilight is upon me, soon night must fall.", movie: "Return of the Jedi" },
  { character: "General Grievous", quote: "You fool! I have been trained in your Jedi arts by Count Dooku.", movie: "Revenge of the Sith" },
  { character: "Princess Leia Organa", quote: "Oh, Han, it's not like that at all. He's my brother.", movie: "Return of the Jedi" },
  { character: "Anakin Skywalker", quote: "Love won't save you, Padme. Only my new powers can do that.", movie: "Revenge of the Sith" },
  { character: "Luke Skywalker", quote: "He will not let me down. He never has.", movie: "Return of the Jedi" },
  { character: "Princess Leia Organa", quote: "This is some rescue. You came in here and you didn't have a plan for getting out?", movie: "A New Hope" },
  { character: "Opening Title", quote: "A Long Time Ago In A Galaxy Far Far Away...", movie: "Every single one of them!" },
  { character: "Han Solo", quote: "Droids don't pull people's arms outta their sockets when they lose... Wookies are known to do that...", movie: "A New Hope" },
  { character: "Princess Leia Organa", quote: "Why you stuck-up, half-witted, scruffy-looking nerf-herder!", movie: "The Empire Strikes Back" },
  { character: "C-3PO", quote: "I suggest a new strategy, R2. Let the wookiee win.", movie: "A New Hope" },
  { character: "Darth Vader", quote: "Don't make me destroy you.", movie: "The Empire Strikes Back" },
  { character: "Han Solo", quote: "One thing's for sure, we're all going to be a lot thinner.", movie: "A New Hope" },
  { character: "Luke Skywalker", quote: "I've got a very bad feeling about this.", movie: "A New Hope" },
  { character: "C-3PO", quote: "R2-D2, you know better than to trust a strange computer!", movie: "The Empire Strikes Back" },
  { character: "Obi-Wan Kenobi", quote: "General Grievous, you're shorter than I expected.", movie: "Revenge of the Sith" },
  { character: "Luke Skywalker", quote: "There's nothing for me here now. I want to learn the ways of the Force and be a Jedi, like my father before me.", movie: "A New Hope" },
  { character: "Admiral Ackbar", quote: "It's a trap!", movie: "Return of the Jedi" },
  { character: "Luke Skywalker", quote: "If there's a bright centre to the universe, you're on the planet that it's farthest from.", movie: "A New Hope" },
  { character: "", quote: "Greed can be a very powerful ally.", movie: "" },
  { character: "C-3PO", quote: "We seem to be made to suffer. It's our lot in life.", movie: "A New Hope" },
  { character: "Luke Skywalker", quote: "Your thoughts betray you father. I feel the good in you. The conflict.", movie: "Return of the Jedi" },
  { character: "Padmé Amidala", quote: "Anakin, you're breaking my heart! And you're going down a path I cannot follow!", movie: "Revenge of the Sith" },
  { character: "Darth Vader", quote: "Just for once, let me look on you with my own eyes.", movie: "Return of the Jedi" },
  { character: "", quote: "Clear your mind must be, if you are to discover the real villains behind this plot.", movie: "" },
  { character: "", quote: "Listen to them, they're dying, R2. Curse my metal body. I wasn't fast enough. It's all my fault. My poor master.", movie: "" },
  { character: "", quote: "Look, Your Worshipfulness, let's get one thing straight... I take orders from one person! Me!", movie: "" },
  { character: "", quote: "I can't do it, R2. I can't go on alone.", movie: "" },
  { character: "", quote: "Sometimes we must do what is requested of us.", movie: "" },
  { character: "Padmé Amidala", quote: "So this is how liberty dies, with thunderous applause.", movie: "Revenge of the Sith" },
  { character: "", quote: "Look, good against remotes is one thing, good against the living, that's something else.", movie: "" },
  { character: "Obi-Wan Kenobi", quote: "Luke, I don't want to lose you to the Emperor the way I lost Vader.", movie: "Return of the Jedi" },
  { character: "Luke Skywalker", quote: "The Force runs strong in my family. My father has it. I have it. And... my sister has it. Yes. It's you, Leia.", movie: "Return of the Jedi" },
  { character: "Yoda", quote: "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.", movie: "The Phantom Menace" },
  { character: "Darth Vader", quote: "You are unwise to lower your defenses...", movie: "A New Hope" },
  { character: "Darth Vader", quote: "I sense something; a presence I've not felt since...", movie: "A New Hope" },
  { character: "Yoda", quote: "Beware of the dark side.", movie: "The Empire Strikes Back" },
  { character: "", quote: "Ready are you? What know you of ready? For eight hundred years have I trained Jedi. My own counsel will I keep on who is to be trained.", movie: "" },
  { character: "", quote: "Don't center on your anxieties, Obi-Wan.", movie: "" },
  { character: "", quote: "Pain, suffering, death I feel. Something terrible has happened. Young Skywalker is in pain. Terrible pain.", movie: "" },
  { character: "Obi-Wan Kenobi", quote: "Only a master of evil, Darth.", movie: "A New Hope" },
  { character: "Emperor Palpatine", quote: "Everything is proceeding as I have foreseen.", movie: "Return of the Jedi" },
  { character: "", quote: "You don't know how hard I found it, signing the order to terminate your life.", movie: "" },
  { character: "", quote: "Dreams pass in time.", movie: "" },
  { character: "Mace Windu", quote: "This party's over.", movie: "Attack of the Clones" },
  { character: "C-3PO", quote: "He's holding a thermal detonator!", movie: "Return of the Jedi" },
  { character: "Anakin Skywalker", quote: "Are you an angel? I've heard the deep space pilots talk about them. They're the most beautiful creatures in the universe.", movie: "The Phantom Menace" },
  { character: "", quote: "You refer to the prophecy of The One, who will bring balance to the Force. You believe it's this boy?", movie: "" },
  { character: "Han Solo", quote: "Scoundrel? Scoundrel? I like the sound of that.", movie: "The Empire Strikes Back" },
  { character: "", quote: "In time, you will learn to trust your feelings. Then, you will be invincible.", movie: "" },
  { character: "", quote: "Without the midi-chlorians, life could not exist, and we would have no knowledge of the Force.", movie: "" },
  { character: "", quote: "There's no mystical energy field that controls my destiny.", movie: "" },
  { character: "Palpatine", quote: "You must repair him! Sir, if any of my circuits or gears will help, I'll gladly donate them.", movie: "Revenge of the Sith" },
  { character: "Yoda", quote: "Size matters not. Look at me. Judge me by my size, do you? Hmm? Hmm.", movie: "The Empire Strikes Back" },
  { character: "", quote: "All who gain power are afraid to lose it.", movie: "" },
  { character: "", quote: "Patience, my blue friend.", movie: "" },
  { character: "", quote: "I can only protect you, I cannot fight a war for you.", movie: "" },
  { character: "Han Solo", quote: "Lando's not a system he's a man!", movie: "The Empire Strikes Back" },
  { character: "", quote: "I don't want to hear anymore about Obi-Wan. The Jedi turned against me! Don't you turn against me!", movie: "" },
  { character: "", quote: "You must feel the force around you. Here, between you, me, the tree, the rock... everywhere! Yes, even between this land and that ship!", movie: "" },
  { character: "", quote: "If so powerful you are, why leave?", movie: "" },
  { character: "", quote: "It is possible that the war itself has been only one further move in some greater game.", movie: "" },
  { character: "", quote: "Do not assume anything. Clear, your mind must be.", movie: "" },
  { character: "Yoda", quote: "Great, kid! Don't get cocky.", movie: "The Empire Strikes Back" },
  { character: "Palpatine", quote: "You can't win. But there are alternatives to fighting.", movie: "Revenge of the Sith" },
  { character: "", quote: "Difficult to see. Always in motion is the future.", movie: "" },
  { character: "Darth Vader", quote: "Good Anakin. Good. Kill him. Kill him now.", movie: "The Empire Strikes Back" },
  { character: "Princess Leia Organa", quote: "Anger, fear, aggression; the dark side of the Force are they. Easily they flow, quick to join you in a fight.", movie: "Return of the Jedi" },
  { character: "", quote: "Luke, you can destroy the Emperor. He has foreseen this. It is your destiny. Join me, and together we can rule the galaxy as father and son.", movie: "" },
  { character: "Luke Skywalker", quote: "I'm not afraid to die.", movie: "A New Hope" },
  { character: "Luke Skywalker", quote: "Mudhole? Slimy? My home this is!", movie: "Return of the Jedi" },
  { character: "Yoda", quote: "You look absolutely beautiful. You truly belong here with us among the clouds.", movie: "The Empire Strikes Back" },
  { character: "", quote: "Either shut him up or shut him down!", movie: "" },
  { character: "Yoda", quote: "Oh my. Space travel sound rather perilous. I can assure you they will never get me on one of those dreadful Star Ships.", movie: "The Phantom Menace" },
  { character: "Luke Skywalker", quote: "I'm Luke Skywalker, I'm here to rescue you.", movie: "" },
  { character: "Han Solo", quote: "Your overconfidence is your weakness.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "Anger, fear, aggression... the dark side are they. Once you start down the dark path, forever will it dominate your destiny.", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "Every generation has a legend. Every journey has a first step. Every saga has a beginning.", movie: "The Empire Strikes Back" },
  { character: "", quote: "Always two there are, no more, no less: a master and an apprentice.", movie: "" },
  { character: "Qui-Gon Jinn", quote: "Victory? Victory, you say? Master Obi-Wan, not victory. The shroud of the Dark Side has fallen. Begun, the Clone War has!", movie: "The Phantom Menace" },
  { character: "", quote: "Uh, we had a slight weapons malfunction, but uh, everything's perfectly all right now.", movie: "" },
  { character: "Princess Leia Organa", quote: "That boy is our last hope.", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "Luminous beings are we. Not this crude matter.", movie: "" },
  { character: "Obi-Wan Kenobi", quote: "Oh, my! What have you done? I'm BACKWARDS. You flea-bitten furball! Only an overgrown mop-head like you would be stupid enough to...", movie: "A New Hope" },
  { character: "", quote: "Luke... Luke... do not... do not underestimate the powers of the Emperor or suffer your father's fate you will.", movie: "" },
  { character: "", quote: "The ability to speak does not make you intelligent.", movie: "" },
  { character: "", quote: "He was meant to root out the Rebels, not give them hope. His sacrifice will only inspire them...", movie: "" },
  { character: "Princess Leia Organa", quote: "You have your moments. Not many of them, but you do have them.", movie: "" },
  { character: "", quote: "The council has granted me permission to train you. You will be a Jedi, I promise.", movie: "" },
  { character: "Darth Vader", quote: "For over a thousand generations, the Jedi Knights were the guardians of peace and justice in the Old Republic.", movie: "A New Hope" },
  { character: "", quote: "Ex-squeeze me, but the mostest safest place would be Gunga City.", movie: "" },
  { character: "", quote: "Boy, it's lucky you have these compartments!", movie: "" },
  { character: "Yoda", quote: "The drums of conflict are my beating heart.", movie: "Return of the Jedi" },
  { character: "Anakin Skywalker", quote: "I find your lack of faith disturbing.", movie: "Attack of the Clones" },
  { character: "", quote: "That's your uncle talking.", movie: "" },
  { character: "Princess Leia Organa", quote: "The Force is strong with him. The son of Skywalker must not become a Jedi.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "I can hold it... I can hold it... I CAN'T HOLD IT!", movie: "A New Hope" },
  { character: "", quote: "In his belly you will find a new definition of pain and suffering as you are slowly digested over a thousand years.", movie: "" },
  { character: "Han Solo", quote: "Then I'll see you in hell!", movie: "A New Hope" },
  { character: "", quote: "He is as clumsy as he is stupid. General, prepare your troops for a surface attack.", movie: "" },
  { character: "", quote: "Pass on what you have learned.", movie: "" },
  { character: "", quote: "From the moment I met you, all those years ago, not a day has gone by when I haven't thought of you.", movie: "" },
  { character: "", quote: "Look, I ain't in this for your revolution, and I'm not in it for you, Princess. I expect to be well paid. I'm in it for the money.", movie: "" },
  { character: "Luke Skywalker", quote: "Luke, you switched off your targeting computer - what's wrong?", movie: "A New Hope" },
  { character: "", quote: "Will someone get this big walking carpet out of my way?", movie: "" },
  { character: "", quote: "Mom, you said that the biggest problem in the universe is no one helps each other.", movie: "" },
  { character: "Han Solo", quote: "Your eyes can deceive you; don't trust them.", movie: "A New Hope" },
  { character: "Princess Leia Organa", quote: "Uh, uh... negative, negative. We had a reactor leak here now. Give us a few minutes to lock it down. Large leak, very dangerous.", movie: "A New Hope" },
  { character: "", quote: "Hmph. Adventure. Heh. Excitement. Heh. A Jedi craves not these things. You are reckless.", movie: "" },
  { character: "Han Solo", quote: "You may dispense with the pleasantries, Commander. I am here to put you back on schedule.", movie: "A New Hope" },
  { character: "", quote: "Master Kenobi, you disappoint me. Yoda holds you in such high esteem. Surely you can do better!", movie: "" },
  { character: "Han Solo", quote: "He's quite clever, you know... for a human being.", movie: "The Empire Strikes Back" },
  { character: "Luke Skywalker", quote: "This is Red 5, I'm going in.", movie: "" },
  { character: "Obi-Wan Kenobi", quote: "Because you are my Son!", movie: "A New Hope" },
  { character: "", quote: "I haven't gone by the name of Obi-Wan since... oh, before you were born.", movie: "" },
  { character: "Luke Skywalker", quote: "He will join us or die, my master.", movie: "The Empire Strikes Back" },
  { character: "", quote: "I think I'm finally getting the hang of this flying business.", movie: "" },
  { character: "", quote: "Never tell me the odds.", movie: "" },
  { character: "Yoda", quote: "And I am C-3PO, human-cyborg relations. And this is my counterpart R2D2.", movie: "The Empire Strikes Back" },
  { character: "", quote: "She may not look like much, but she's got it where it counts, kid.", movie: "" },
  { character: "", quote: "Jedi business. Go back to your drinks.", movie: "" },
  { character: "Yoda", quote: "It's not wise to upset a Wookiee.", movie: "Revenge of the Sith" },
  { character: "Han Solo", quote: "I don't know who you are or where you've come from, but from now on you'll do as I say, okay?", movie: "The Empire Strikes Back" },
  { character: "Princess Leia Organa", quote: "How you doin\\\" Chewbacca? Still hanging around with this loser?", movie: "A New Hope" },
  { character: "Yoda", quote: "Some day you're gonna be wrong, I just hope I'm there to see it.", movie: "Attack of the Clones" },
  { character: "Darth Vader", quote: "The ability to destroy a planet is insignificant next to the power of the Force.", movie: "The Empire Strikes Back" },
  { character: "", quote: "Crush them! Make them suffer!", movie: "" },
  { character: "C-3PO", quote: "Use my knowledge, I beg you.", movie: "Return of the Jedi" },
  { character: "Luke Skywalker", quote: "I felt a great disturbance in the force, as if millions of voices suddenly cried out in terror and were suddenly silenced.", movie: "A New Hope" },
  { character: "Han Solo", quote: "Anakin, please tell me this isn't another of your patented rescues where we'll require the whole Republic army to get safely away.", movie: "Return of the Jedi" },
  { character: "C-3PO", quote: "I have you now!", movie: "A New Hope" },
  { character: "", quote: "But which one was destroyed? The master or the apprentice?", movie: "" },
  { character: "Yoda", quote: "I don't believe what I'm hearing... Obi-Wan was right. You've changed.", movie: "Revenge of the Sith" },
  { character: "Darth Vader", quote: "Always on the move.", movie: "The Empire Strikes Back" },
  { character: "Obi-Wan Kenobi", quote: "The Dark Side of the Force is the pathway to many abilities some consider to be... Unnatural.", movie: "A New Hope" },
  { character: "Yoda", quote: "When 900 years old, you reach... Look as good, you will not.", movie: "" },
  { character: "Han Solo", quote: "You were my brother, Anakin. I loved you.", movie: "A New Hope" },
  { character: "Darth Vader", quote: "Army or not. You must realize, you are doomed.", movie: "A New Hope" },
  { character: "", quote: "Hold your fire. There's no life forms. It must have short-circuited.", movie: "" },
  { character: "", quote: "Captain, being held by you isn't quite enough to get me excited.", movie: "" },
  { character: "", quote: "You can forget your troubles with those Imperial slugs. I told you I'd outrun 'em. Don't everyone thank me at once.", movie: "" },
  { character: "Yoda", quote: "You can't win, Darth. Strike me down, and I will become more powerful than you could possibly imagine.", movie: "Attack of the Clones" },
  { character: "Han Solo", quote: "You'll be dead!", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "Nooooooooooooooooooo!", movie: "A New Hope" },
  { character: "", quote: "Attachment is forbidden. Possession is forbidden. Compassion, which I would define as unconditional love, is essential to a Jedi's life.", movie: "" },
  { character: "", quote: "I sense a great deal of confusion in you, young Skywalker. There's much fear that clouds your judgement.", movie: "" },
  { character: "", quote: "Keep your concentration here and now, where it belongs.", movie: "" },
  { character: "Yoda", quote: "Into exile I must go, failed I have.", movie: "The Phantom Menace" },
  { character: "Han Solo", quote: "Watch your mouth kid, or you'll find yourself floating home.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "Aren't you a little short for a stormtrooper?", movie: "A New Hope" },
  { character: "Luke Skywalker", quote: "Truly wonderful, the mind of a child is.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "Laugh it up, Fuzz ball.", movie: "Revenge of the Sith" },
  { character: "", quote: "Promise. Promise me you will train the boy. He... is the chosen one... he will bring balance. Train him.", movie: "" },
  { character: "Darth Vader", quote: "Impressive, most impressive.", movie: "" },
  { character: "Darth Vader", quote: "Oh my goodness, shut me down! Machines making machines. How perverse.", movie: "A New Hope" },
  { character: "", quote: "I'm Luke Skywalker. I'm here to rescue you.", movie: "" },
  { character: "Princess Leia Organa", quote: "Keep your distance, Chewie, but don't, y'know, look like you're keeping your distance.", movie: "The Empire Strikes Back" },
  { character: "Princess Leia Organa", quote: "Don't get technical with me. What mission? What are you talking about? I've just about had enough of you. Go that way, you'll be malfunctioning in a day you near-sighted scrap pile.", movie: "The Empire Strikes Back" },
  { character: "Obi-Wan Kenobi", quote: "I have waited a long time for this moment, my little green friend. At last, the Jedi are no more.", movie: "A New Hope" },
  { character: "Luke Skywalker", quote: "Blind we are, if creation of this clone army we could not see.", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "Asteroids do not concern me, Admiral. I want that ship, not excuses.", movie: "The Empire Strikes Back" },
  { character: "Luke Skywalker", quote: "A tremor in the Force. The last time I felt it was in the presence of my old master.", movie: "Return of the Jedi" },
  { character: "Darth Vader", quote: "Bargain rather than fight? He's no Jedi.", movie: "Return of the Jedi" },
  { character: "", quote: "The Force can have a strong influence on the weak-minded.", movie: "" },
  { character: "Yoda", quote: "Aaaaaaargh!", movie: "The Empire Strikes Back" },
  { character: "", quote: "Now, be brave and don't look back. Don't look back.", movie: "" },
  { character: "", quote: "Patience, use the Force, think!", movie: "" },
  { character: "Qui-Gon Jinn", quote: "I don't like you either. You just watch yourself. We're wanted men. I have the death sentence on twelve systems.", movie: "Revenge of the Sith" },
  { character: "Darth Vader", quote: "The Jedi are extinct, their fire has gone out of the universe. You, my friend, are all that's left of their religion.", movie: "The Empire Strikes Back" },
  { character: "", quote: "I hope so Commander, for your sake. The Emperor is not as forgiving as I am.", movie: "" },
  { character: "Luke Skywalker", quote: "What a piece of junk!", movie: "A New Hope" },
  { character: "Yoda", quote: "I'm getting too old for this sort of thing.", movie: "The Empire Strikes Back" },
  { character: "Han Solo", quote: "You fool! I've been trained in your Jedi arts by Count Dooku.", movie: "The Empire Strikes Back" },
  { character: "Qui-Gon Jinn", quote: "Make, at least, 20 people smile in a day.", movie: "Revenge of the Sith" },
  { character: "Darth Vader", quote: "Mmm. Lost a planet, Master Obi-Wan has. How embarrassing.", movie: "A New Hope" },
  { character: "Opening Title", quote: "Bring 'em on, I'd prefer a straight fight to all this sneaking around.", movie: "" },
  { character: "Luke Skywalker", quote: "In my experience, there's no such thing as luck.", movie: "A New Hope" },
  { character: "Han Solo", quote: "I guess you don't know everything about women yet.", movie: "The Empire Strikes Back" },
  { character: "C-3PO", quote: "Evacuate in our moment of triumph? I think you overestimate their chances.", movie: "A New Hope" },
  { character: "", quote: "To a dark place this line of thought will carry us. Great care we must take.", movie: "" },
  { character: "Palpatine", quote: "All his life has he looked away... to the future, to the horizon. Never his mind on where he was. Hmm? What he was doing.", movie: "Revenge of the Sith" },
  { character: "", quote: "I was not elected to watch my people suffer and die while you discuss this invasion in a committee!", movie: "" },
  { character: "Darth Vader", quote: "Wonderful girl. Either I'm going to kill her or I'm beginning to like her.", movie: "The Empire Strikes Back" },
  { character: "", quote: "Why do I sense we've picked up another pathetic life-form?", movie: "" },
  { character: "", quote: "These blast points - too accurate for sandpeople. Only imperial stormtroopers are so precise.", movie: "" },
  { character: "Han Solo", quote: "How ya feeling kid? You don't look so bad to me. You look strong enough to pull the ears off a gundark.", movie: "A New Hope" },
  { character: "", quote: "No, my father didn't fight in the Clone Wars. He was a navigator on a spice freighter.", movie: "" },
  { character: "Obi-Wan Kenobi", quote: "You were to bring balance to the force, not leave it in darkness.", movie: "A New Hope" },
  { character: "Yoda", quote: "Mesa called JaJa Binks, mesa youse humble servant!", movie: "The Empire Strikes Back" },
  { character: "C-3PO", quote: "A Jedi uses the force for knowledge and defense, never for attack.", movie: "The Empire Strikes Back" },
  { character: "Obi-Wan Kenobi", quote: "I don't like sand. It's coarse and rough and irritating and it gets everywhere. Not like here. Here everything is soft and smooth.", movie: "Revenge of the Sith" },
  { character: "Admiral Motti", quote: "Me? A Master? I'm overwhelmed, sir. But the Council elects its own members. They will never accept this.", movie: "A New Hope" },
  { character: "Luke Skywalker", quote: "One truth, one hate.", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "Thank the maker!", movie: "Revenge of the Sith" },
  { character: "Mon Mothma", quote: "Many Bothans died to bring us this information.", movie: "" },
  { character: "Mace Windu", quote: "Help me Obi-Wan Kenobi, you're my only hope.", movie: "The Phantom Menace" },
  { character: "Darth Vader", quote: "The Force is what gives a Jedi his power. It's an energy field created by all living things. It surrounds us and penetrates us. It binds the galaxy together.", movie: "A New Hope" },
  { character: "", quote: "If you have warriors, now is the time.", movie: "" },
  { character: "Han Solo", quote: "This will be a day long remembered. It has seen the end of Kenobi, and will soon see the end of the rebellion.", movie: "A New Hope" },
  { character: "", quote: "I recognized your foul stench when I was brought on board.", movie: "" },
  { character: "", quote: "You've never heard of the Millennium Falcon?... It's the ship that made the Kessel run in less than 12 parsecs.", movie: "" },
  { character: "Han Solo", quote: "Son, my place is here, my future is here. It is time for you to let go.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "We are indebted to you for your bravery, Obi-Wan Kenobi. And you, young Skywalker; we will watch your career with great interest.", movie: "Attack of the Clones" },
  { character: "Yoda", quote: "I'm altering the deal. Pray I don't alter it any further.", movie: "Attack of the Clones" },
  { character: "", quote: "To be angry is to be human.", movie: "" },
  { character: "Han Solo", quote: "You came in that thing? You're braver than I thought.", movie: "A New Hope" },
  { character: "Luke Skywalker", quote: "Attachment leads to jealousy. The shadow of greed that is.", movie: "The Empire Strikes Back" },
  { character: "Princess Leia Organa", quote: "You know better than to trust a strange computer.", movie: "The Empire Strikes Back" },
  { character: "", quote: "Someday I'll be the most powerful Jedi ever.", movie: "" },
  { character: "", quote: "You were the Chosen one!", movie: "" },
  { character: "Yoda", quote: "Traveling through hyperspace ain't like dusting crops, farm boy.", movie: "The Empire Strikes Back" },
  { character: "Han Solo", quote: "You can either profit by this or be destroyed. It's your choice, but I warn you not to underestimate my power.", movie: "The Empire Strikes Back" },
  { character: "C-3PO", quote: "R2, why did you have to be so brave?", movie: "" },
  { character: "Darth Vader", quote: "Jabba, you're a wonderful human being.", movie: "The Empire Strikes Back" },
  { character: "Darth Vader", quote: "All who gain power are afraid to lose it.", movie: "Return of the Jedi" },
  { character: "Theed Palace Guard", quote: "Help me Obi-Wan Kenobi. You're my only hope.", movie: "The Phantom Menace" },
  { character: "Yoda", quote: "You're asking me to be rational. That is something I know I cannot do. Believe me, I wish I could just wish away my feelings, but I can't.", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "What if the democracy we thought we were serving no longer exists, and the Republic has become the very evil we've been fighting to destroy?", movie: "Attack of the Clones" },
  { character: "Obi-Wan Kenobi", quote: "Hello. I don't believe we have been introduced. R2-D2? A pleasure to meet you. I am C-3PO, Human-Cyborg Relations.", movie: "Revenge of the Sith" },
  { character: "Padmé Amidala", quote: "Faith in your new apprentice, misplaced may be. As is your faith in the dark side of the Force.", movie: "Attack of the Clones" },
  { character: "Anakin Skywalker", quote: "Give yourself to the Dark Side. It is the only way you can save your friends. Yes your thoughts betray you.", movie: "Attack of the Clones" },
  { character: "Padmé Amidala", quote: "You must unlearn what you have learned.", movie: "Attack of the Clones" },
  { character: "Obi-Wan Kenobi", quote: "Now don't you forget this! Why I should stick my neck out for you is far beyond my capacity!", movie: "Revenge of the Sith" },
  { character: "Padmé Amidala", quote: "Feel the Force!", movie: "Attack of the Clones" },
  { character: "Han Solo", quote: "I am not training him.", movie: "The Empire Strikes Back" },
  { character: "Qui-Gon Jinn", quote: "Something's happening. I'm not the Jedi I should be. I want more. And I know I shouldn't.", movie: "The Phantom Menace" },
  { character: "", quote: "Feel, don't think.", movie: "" },
  { character: "Han Solo", quote: "I've been waiting for you, Obi-Wan. We meet again, at last. The circle is now complete. When I left you, I was but the learner; now I am the master.", movie: "A New Hope" },
  { character: "Princess Leia Organa", quote: "I will not condone a course of action that will lead us to war.", movie: "A New Hope" },
  { character: "Darth Vader", quote: "At the thought of not being with you, I can't breathe.", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "Don't try to frighten us with your sorcerous ways, Lord Vader.", movie: "The Empire Strikes Back" },
  { character: "Han Solo", quote: "It is obvious that this contest cannot be decided by our knowledge of the Force... but by our skills with a lightsaber.", movie: "Return of the Jedi" },
  { character: "Darth Vader", quote: "Wipe them out. All of them.", movie: "The Empire Strikes Back" },
  { character: "Jabba the Hutt", quote: "Look, sir: Droids.", movie: "Return of the Jedi" },
  { character: "Han Solo", quote: "If you're not with me, then you're my enemy.", movie: "Return of the Jedi" },
  { character: "C-3PO", quote: "May the force be with you.", movie: "Return of the Jedi" },
  { character: "Obi-Wan Kenobi", quote: "A Jedi Knight? Jeez, I'm out of it for a little while, everyone gets delusions of grandeur!", movie: "A New Hope" },
  { character: "Palpatine", quote: "These Federation types are cowards. The negotiations will be short.", movie: "Revenge of the Sith" },
  { character: "Lando Calrissian", quote: "Your powers are weak, old man.", movie: "The Empire Strikes Back" },
  { character: "Obi-Wan Kenobi", quote: "Through the force, things you will see. Other places. The future... the past. Old friends long gone.", movie: "Attack of the Clones" },
  { character: "Han Solo", quote: "Hokey religions and ancient weapons are no match for a good blaster at your side, kid.", movie: "A New Hope" },
  { character: "Han Solo", quote: "Clear your mind of questions.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "Great shot kid, that was one in a million.", movie: "Return of the Jedi" },
  { character: "Anakin Skywalker", quote: "Wars not make one great.", movie: "The Phantom Menace" },
  { character: "Admiral Motti", quote: "Let the Wookiee win.", movie: "A New Hope" },
  { character: "Padmé Amidala", quote: "This is some rescue! You came in here, but didn't you have a plan for getting out?", movie: "Revenge of the Sith" },
  { character: "Shmi Skywalker", quote: "That... is why you fail.", movie: "Attack of the Clones" },
  { character: "Yoda", quote: "I don't sense anything.", movie: "Revenge of the Sith" },
  { character: "Mon Mothma", quote: "Mos Eisley spaceport. You will never find a more wretched hive of scum and villainy.", movie: "Return of the Jedi" },
  { character: "Princess Leia Organa", quote: "Not to worry. We're still flying half a ship.", movie: "A New Hope" },
  { character: "Obi-Wan Kenobi", quote: "Another happy landing.", movie: "A New Hope" },
  { character: "Yoda", quote: "Rejoice for those around you who transform into the Force.", movie: "Revenge of the Sith" },
  { character: "Darth Vader", quote: "The Force is strong with this one.", movie: "A New Hope" },
  { character: "Princess Leia Organa", quote: "I see you becoming the greatest of all the Jedi, Anakin. Even more powerful than Master Yoda.", movie: "A New Hope" },
  { character: "Han Solo", quote: "No. I am your Father.", movie: "A New Hope" },
  { character: "Darth Vader", quote: "It is too late for me, son. The Emperor will show you the true nature of the Force. He is your master now.", movie: "Return of the Jedi" },
  { character: "Palpatine", quote: "The Chancellor's right, Senator. We'll be quite safe. He won several cups for airspeeder racing back on Naboo.", movie: "Attack of the Clones" },
  { character: "Darth Vader", quote: "No! Try not. Do, or do not. There is no try.", movie: "The Empire Strikes Back" },
  { character: "Padmé Amidala", quote: "Anything is possible.", movie: "Attack of the Clones" },
  { character: "Princess Leia Organa", quote: "Your arrogance blinds you.", movie: "A New Hope" },
  { character: "Yoda", quote: "I'm haunted by the kiss that you should never have given me. My heart is beating... hoping that kiss will not become a scar.", movie: "Attack of the Clones" },
  { character: "C-3PO", quote: "Only a sith deals in absolutes.", movie: "The Empire Strikes Back" },
  { character: "Anakin Skywalker", quote: "We live in a real world, Annie. Come back to it.", movie: "Attack of the Clones" },
  { character: "Obi-Wan Kenobi", quote: "So, what do you think? You think a princess and a guy like me...", movie: "Revenge of the Sith" },
  { character: "Han Solo", quote: "Don't center on your anxieties, Obi-Wan. Keep your concentration here and now, where it belongs.", movie: "A New Hope" },
  { character: "Darth Vader", quote: "I'll be careful.", movie: "The Empire Strikes Back" },
  { character: "C-3PO", quote: "Who's the more foolish: the fool, or the fool who follows him?", movie: "Return of the Jedi" },
  { character: "Princess Leia Organa", quote: "General, prepare your men.", movie: "A New Hope" },
  { character: "Padmé Amidala", quote: "The strong survive, the weak die. That's the way the galaxy works. The day we forgot that, we became everyone's lackey.", movie: "Attack of the Clones" },
  { character: "Luke Skywalker", quote: "We have powerful friends. You're going to regret this.", movie: "Return of the Jedi" },
  { character: "Yoda", quote: "I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything.", movie: "The Empire Strikes Back" },
  { character: "C-3PO", quote: "Maybe you'd like it back in your cell, your highness.", movie: "A New Hope" },
  { character: "Darth Vader", quote: "I want them alive, no disintegrations!", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "A Jedi must have the deepest commitment, the most serious mind.", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "I think my eyes are getting better. Instead of a big dark blur, I see a big light blur.", movie: "The Empire Strikes Back" },
  { character: "Luke Skywalker", quote: "We have a new enemy, the young Rebel who destroyed the Death Star. I have no doubt this boy is the offspring of Anakin Skywalker.", movie: "A New Hope" },
  { character: "C-3PO", quote: "Jabba's put a price on your head so large, every bounty hunter in the galaxy will be looking for you.", movie: "The Empire Strikes Back" },
  { character: "Obi-Wan Kenobi", quote: "My parts are showing? Oh, my goodness, oh!", movie: "Revenge of the Sith" },
  { character: "Yoda", quote: "That's no moon, it's a space station.", movie: "Return of the Jedi" },
  { character: "Darth Vader", quote: "The Force is strong with you. A powerful Sith you will become. Henceforth, you shall be known as Darth... Vader.", movie: "A New Hope" },
  { character: "Palpatine", quote: "You slimy, double-crossing, no-good swindler. You've got a lot of guts coming here, after what you pulled.", movie: "Revenge of the Sith" },
  { character: "Darth Vader", quote: "Soon, I will have a new apprentice. One far younger, and more powerful.", movie: "The Empire Strikes Back" },
  { character: "Padmé Amidala", quote: "You're all clear, kid! Now let's blow this thing and go home!", movie: "Attack of the Clones" },
  { character: "Yoda", quote: "He's the brains, sweetheart!", movie: "Attack of the Clones" },
  { character: "Anakin Skywalker", quote: "You will find that many of the truths we cling to depend greatly on our own point of view.", movie: "Attack of the Clones" },
  { character: "Obi-Wan Kenobi", quote: "I'm a person, and my name is Anakin!", movie: "Revenge of the Sith" },
  { character: "Padmé Amidala", quote: "This station is now the ultimate power in the universe! I suggest we use it.", movie: "Attack of the Clones" },
  { character: "Han Solo", quote: "Hold me, like you did by the lake on Naboo; so long ago when there was nothing but our love. No politics, no plotting, no war.", movie: "The Empire Strikes Back" },
  { character: "Yoda", quote: "You can't stop the change any more than you can stop the suns from setting.", movie: "Attack of the Clones" },
  { character: "Han Solo", quote: "Death is a natural part of life.", movie: "Return of the Jedi" },
];

module.exports = function() {
  return quotes[Math.floor(Math.random() * quotes.length)].quote
}

module.exports.extended = function() {
  return quotes[Math.floor(Math.random() * quotes.length)]
}

module.exports.quotes = quotes
